name: Build iOS App

# allow manual trigger
on: workflow_dispatch

# <— add this!
permissions:
  contents: read     # for checkout, pub get, build…
  actions: read      # <<< give permission to download/upload artifact actions

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - run: flutter doctor -v

      - run: flutter pub get

      - run: flutter build ios --debug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-debug-build
          path: build/ios/iphoneos/Runner.app
